name: setup-gradle-composite
description: Set up Java and Gradle for the checked-out repository.
runs:
  using: composite
  steps:
    - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
      with:
        distribution: temurin
        java-version: '21'
    - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808
